version: 2
updates:
  # .NET dependencies
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "localstack-dotnet/maintainers"
    assignees:
      - "localstack-dotnet/maintainers"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      # Group AWS SDK updates together
      aws-sdk:
        patterns:
          - "AWSSDK.*"
          - "AWS.*"
      # Group Microsoft packages together
      microsoft:
        patterns:
          - "Microsoft.*"
          - "System.*"
      # Group testing packages together
      testing:
        patterns:
          - "xunit*"
          - "*Test*"
          - "coverlet*"
          - "FluentAssertions*"
      # Group build and tooling packages
      build-tools:
        patterns:
          - "Cake.*"
          - "GitVersion*"
          - "Nuke.*"
    ignore:
      # Ignore patch updates for stable dependencies
      - dependency-name: "Microsoft.Extensions.*"
        update-types: ["version-update:semver-patch"]

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "localstack-dotnet/maintainers"
    commit-message:
      prefix: "ci"
      include: "scope"
