name: build-ubuntu

on:
  push:
    paths-ignore:
      - "**.md"
      - LICENSE
    branches:
      - "master"
  pull_request:
    paths-ignore:
      - "**.md"
      - LICENSE
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Init
        run: chmod +x ./build.sh

      - name: Install NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Setup Testspace
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}

      - name: Install .NET 8
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.x"

      - name: Install .NET 9
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "9.0.x"

      - name: Build
        run: ./build.sh --target build

      - name: Run Tests
        run: ./build.sh --target tests --skipFunctionalTest false --exclusive

      - name: Push result to Testspace server
        run: |
          testspace [linux]**/*.trx
        if: always()