name: Dependency Review

on:
  pull_request:
    branches:
      - master
      - "feature/*"

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    name: "Dependency Review"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Dependency Review"
        uses: actions/dependency-review-action@v4
        with:
          # Fail the check if a vulnerability with 'moderate' severity or higher is found.
          fail-on-severity: moderate
          # Always post a summary of the check as a comment on the PR.
          comment-summary-in-pr: always