name: "Auto Publish to GitHub Packages"

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - LICENSE
      - ".github/**"
      - "docs/**"

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true

jobs:
  auto-publish:
    name: "Auto Publish Development Build"
    runs-on: ubuntu-22.04
    if: github.repository == 'localstack-dotnet/localstack-dotnet-client'
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    permissions:
      contents: read
      packages: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Setup .NET SDK"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: "Cache NuGet packages"
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json', '**/*.csproj', '**/Directory.Packages.props') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: "Make build script executable"
        run: chmod +x ./build.sh

      - name: "Build & Test"
        run: ./build.sh --target tests --skipFunctionalTest true

      - name: "Setup GitHub Packages Configuration"
        run: |
          echo "📝 Backing up original nuget.config..."
          cp nuget.config nuget.config.backup
          
          echo "🔧 Using GitHub-optimized nuget.config..."
          cp .github/nuget.config nuget.config
          
          echo "🔐 Adding GitHub Packages authentication..."
          dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json \
            --name github-packages \
            --username ${{ github.actor }} \
            --password ${{ secrets.GITHUB_TOKEN }} \
            --store-password-in-clear-text

      - name: "Pack & Publish LocalStack.Client"
        run: |
          echo "🔨 Building and publishing LocalStack.Client package..."
          ./build.sh --target nuget-pack-and-publish \
            --package-source github \
            --package-id LocalStack.Client \
            --use-directory-props-version true \
            --branch-name ${{ github.ref_name }} \
            --package-secret ${{ secrets.GITHUB_TOKEN }}

      - name: "Pack & Publish LocalStack.Client.Extensions"
        run: |
          echo "🔨 Building and publishing LocalStack.Client.Extensions package..."
          ./build.sh --target nuget-pack-and-publish \
            --package-source github \
            --package-id LocalStack.Client.Extensions \
            --use-directory-props-version true \
            --branch-name ${{ github.ref_name }} \
            --package-secret ${{ secrets.GITHUB_TOKEN }}

      - name: "Upload Package Artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: "dev-packages-${{ github.run_number }}"
          path: |
            artifacts/*.nupkg
            artifacts/*.snupkg
          retention-days: 7

      - name: "Generate Build Summary"
        run: |
          echo "📦 Generating build summary..."
          ./build.sh --target workflow-summary \
            --use-directory-props-version true \
            --branch-name ${{ github.ref_name }}
